<?php

/**
 * @file
 * Contains iitb_academic_news.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iitb_academic_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iitb_academic_news module.
    case 'help.page.iitb_academic_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('News Content Type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function iitb_academic_news_theme() {
  return [
    'iitb_academic_news' => [
      'render element' => 'children',
    ],
  ];
}
