<?php

/**
 * @file
 * Contains iitb_academic_faculty.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iitb_academic_faculty_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iitb_academic_faculty module.
    case 'help.page.iitb_academic_faculty':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function iitb_academic_faculty_theme() {
  return [
    'iitb_academic_faculty' => [
      'render element' => 'children',
    ],
  ];
}
