<?php

use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\field\Entity\FieldConfig;

/**************************************************************/

function iitb_academic_course_details_install() {

	/**********************************************************************************/

	$config_course_details_view_display = \Drupal::config('core.entity_view_display.node.course_allotment.default');

	$config_course_details_view_display_dependencies=$config_course_details_view_display->get('dependencies');
 	if(!in_array("field.field.node.course_allotment.field_course_name_ref",
 		$config_course_details_view_display_dependencies['config'])) {
 	 	array_push($config_course_details_view_display_dependencies['config'], 'field.field.node.course_allotment.field_course_name_ref');
  	}

	$new_field_array_view_display= array(
          'weight'=> 106,
          'label'=> 'above',
          'settings'=> array(
            'link'=> 'true',
          ),
          'third_party_settings'=> array(),
          'type'=> 'entity_reference_label',
          'region'=> 'content',
    );
	
	$config_course_details_view_display_fields=$config_course_details_view_display->get('content');
	$config_course_details_view_display_fields['field_course_name_ref']=$new_field_array_view_display;

	\Drupal::configFactory()
	->getEditable('core.entity_view_display.node.course_allotment.default')
	->set('dependencies',$config_course_details_view_display_dependencies)
	->set('content',$config_course_details_view_display_fields)
	->save(TRUE);

	/**********************************************************************************/

	/**********************************************************************************/

	$config_course_details_form_display = \Drupal::config('core.entity_form_display.node.course_allotment.default');

	$config_course_details_form_display_dependencies=$config_course_details_form_display->get('dependencies');
 	if(!in_array("field.field.node.course_allotment.field_course_name_ref",
 		$config_course_details_form_display_dependencies['config'])) {
 	 	array_push($config_course_details_form_display_dependencies['config'], 'field.field.node.course_allotment.field_course_name_ref');
  	}

	$new_field_array_form_display= array(
		'weight'=> 126,
		'settings'=> array(
	   		'match_operator'=> 'CONTAINS',
	   		'size'=> 60,
	   		'placeholder'=> ''
			),
		'third_party_settings'=> array(),
		'type'=> 'entity_reference_autocomplete',
		'region'=> 'content',
	);

		$config_course_details_form_display_fields=$config_course_details_form_display->get('content');
		$config_course_details_form_display_fields['field_course_name_ref']=$new_field_array_form_display;

		\Drupal::configFactory()
		->getEditable('core.entity_form_display.node.course_allotment.default')
		->set('dependencies',$config_course_details_form_display_dependencies)
		->set('content',$config_course_details_form_display_fields)
		->save(TRUE);

		/**********************************************************************************/

}

function iitb_academic_course_details_uninstall(){

	/**********************************************************************************/

	$config_course_details_view_display = \Drupal::config('core.entity_view_display.node.course_allotment.default');

	$config_course_details_view_display_dependencies=$config_course_details_view_display->get('dependencies');
	if (($key = array_search('field.field.node.course_allotment.field_course_name_ref', $config_course_details_view_display_dependencies['config'])) !== false) {
		unset($config_course_details_view_display_dependencies['config'][$key]);
	}

	$config_course_details_view_display_fields=$config_course_details_view_display->get('content');
	if (array_key_exists("field_course_name_ref",$config_course_details_view_display_fields)){
		unset($config_course_details_view_display_fields['field_course_name_ref']);
	}

	\Drupal::configFactory()
		->getEditable('core.entity_view_display.node.course_allotment.default')
		->set('dependencies',$config_course_details_view_display_dependencies)
		->set('content',$config_course_details_view_display_fields)
		->save(TRUE);

	/**********************************************************************************/

	/**********************************************************************************/

	$config_course_details_form_display = \Drupal::config('core.entity_form_display.node.course_allotment.default');

	$config_course_details_form_display_dependencies=$config_course_details_form_display->get('dependencies');
	if (($keys = array_search('field.field.node.course_allotment.field_course_name_ref', $config_course_details_form_display_dependencies['config'])) !==false) {
		unset($config_course_details_form_display_dependencies['config'][$keys]);
	} 

	$config_course_details_form_display_fields=$config_course_details_form_display->get('content');
	if (array_key_exists("field_course_name_ref", $config_course_details_form_display_fields)){
		unset($config_course_details_form_display_fields['field_course_name_ref']);
	}

	\Drupal::configFactory()
	->getEditable('core.entity_form_display.node.course_allotment.default')
	->set('dependencies',$config_course_details_form_display_dependencies)
	->set('content',$config_course_details_form_display_fields)
	->save(TRUE);

	/**********************************************************************************/

	\Drupal::configFactory()->getEditable('core.entity_form_display.node.course_details.default')->delete();
	\Drupal::configFactory()->getEditable('core.entity_view_display.node.course_details.default')->delete();
	\Drupal::configFactory()->getEditable('core.entity_view_display.node.course_details.teaser')->delete();
	\Drupal::configFactory()->getEditable('field.field.node.course_details.body')->delete();
	\Drupal::configFactory()->getEditable('field.field.node.course_details.field_course_code')->delete();
	\Drupal::configFactory()->getEditable('field.field.node.course_details.field_course_texts')->delete();
	\Drupal::configFactory()->getEditable('field.field.node.course_details.field_course_title')->delete();
	\Drupal::configFactory()->getEditable('field.field.node.course_details.field_lecture_credit')->delete();
	\Drupal::configFactory()->getEditable('field.field.node.course_details.field_practical_credit')->delete();
	\Drupal::configFactory()->getEditable('field.field.node.course_details.field_total_credits')->delete();
	\Drupal::configFactory()->getEditable('field.field.node.course_details.field_tutorial_credit')->delete();
	\Drupal::configFactory()->getEditable('field.storage.node.field_course_code')->delete();
	\Drupal::configFactory()->getEditable('field.storage.node.field_course_texts')->delete();
	\Drupal::configFactory()->getEditable('field.storage.node.field_course_title')->delete();
	\Drupal::configFactory()->getEditable('field.storage.node.field_lecture_credit')->delete();
	\Drupal::configFactory()->getEditable('field.storage.node.field_practical_credit')->delete();
	\Drupal::configFactory()->getEditable('field.storage.node.field_total_credits')->delete();
	\Drupal::configFactory()->getEditable('field.storage.node.field_tutorial_credit')->delete();
	\Drupal::configFactory()->getEditable('node.type.course_details.yml')->delete();
	
	\Drupal::configFactory()->getEditable('field.field.node.course_allotment.field_course_name_ref')->delete();
	\Drupal::configFactory()->getEditable('field.storage.node.field_course_name_ref')->delete();

}